version: '3.4'

services:
  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=myStong_Password123# 
  td.web:
    image: ${DOCKER_REGISTRY-}tdweb
    ports:
         - 8001:80
    build:
      context: .
      dockerfile: TD.Web/Dockerfile
    depends_on: 
      - SqlServerDb
  td.frontend:
    image: ${DOCKER_REGISTRY-}tdfrontend
    ports:
      - 5001:5001
    build: 
       context: ./TD.Web/TD.Web.React
       dockerfile: Dockerfile
    

