apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 encoded 'postgres'
  POSTGRES_PASSWORD: c2VjdXJlQDEyMw==  # base64 encoded 'secure@123'
