apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-server
  labels:
    app: postgres-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-server
  template:
    metadata:
      labels:
        app: postgres-server
    spec:
      containers:
        - name: postgres-server
          image: postgres:14 
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: mydatabase  # Optional: You can keep this hardcoded or add it to the secret
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "1"
